import Foundation

/// All 118 elements. Facts are written for an early reader: one short sentence,
/// something you could point at in the real world.
enum Elements {

    static let all: [ChemElement] = [
        ChemElement(1, "H", "Hydrogen", .nonmetal, .gas, tint: 0x9FD8FF,
                    "The lightest thing in the universe. Stars are mostly made of it."),
        ChemElement(2, "He", "Helium", .nobleGas, .gas, tint: 0xFFD98A,
                    "Fills party balloons and makes your voice go squeaky."),
        ChemElement(3, "Li", "Lithium", .alkaliMetal, .solid, tint: 0xE2E6EC,
                    "So light it floats on water. It powers phone batteries."),
        ChemElement(4, "Be", "Beryllium", .alkalineEarth, .solid, tint: 0xC9D2CB,
                    "Light but very strong, so space telescopes are made of it."),
        ChemElement(5, "B", "Boron", .metalloid, .solid, tint: 0x6B5F52,
                    "Makes tough glass that doesn't crack when it gets hot."),
        ChemElement(6, "C", "Carbon", .nonmetal, .solid, tint: 0x525A66,
                    "Pencil lead and diamonds are both carbon. Same stuff, different shape."),
        ChemElement(7, "N", "Nitrogen", .nonmetal, .gas, tint: 0xBFD4FF,
                    "Most of the air you breathe is nitrogen."),
        ChemElement(8, "O", "Oxygen", .nonmetal, .gas, tint: 0x9BE7FF,
                    "The part of the air your body actually needs."),
        ChemElement(9, "F", "Fluorine", .halogen, .gas, tint: 0xF2F5C4,
                    "It goes in toothpaste to keep your teeth strong."),
        ChemElement(10, "Ne", "Neon", .nobleGas, .gas, tint: 0xFF6B4A,
                    "Glows bright orange-red in shop signs."),
        ChemElement(11, "Na", "Sodium", .alkaliMetal, .solid, tint: 0xE6E9EE,
                    "Half of salt. On its own it fizzes and pops in water."),
        ChemElement(12, "Mg", "Magnesium", .alkalineEarth, .solid, tint: 0xD8DCE0,
                    "Burns with a blinding white flame."),
        ChemElement(13, "Al", "Aluminium", .otherMetal, .solid, tint: 0xD5DAE2,
                    "Drink cans and cooking foil are made of it."),
        ChemElement(14, "Si", "Silicon", .metalloid, .solid, tint: 0x6E7683,
                    "Sand turns into the chips inside computers."),
        ChemElement(15, "P", "Phosphorus", .nonmetal, .solid, tint: 0xFFE066,
                    "The stuff on the tip of a match head."),
        ChemElement(16, "S", "Sulfur", .nonmetal, .solid, tint: 0xFFD73F,
                    "Bright yellow. Burning it smells like a just-struck match."),
        ChemElement(17, "Cl", "Chlorine", .halogen, .gas, tint: 0xA8D63C,
                    "Keeps swimming pools clean. It's the other half of salt."),
        ChemElement(18, "Ar", "Argon", .nobleGas, .gas, tint: 0xB07CFF,
                    "Sits inside light bulbs doing absolutely nothing."),
        ChemElement(19, "K", "Potassium", .alkaliMetal, .solid, tint: 0xE4E1D8,
                    "Bananas are full of it."),
        ChemElement(20, "Ca", "Calcium", .alkalineEarth, .solid, tint: 0xE8E6DE,
                    "Builds your bones and teeth. Milk is full of it."),
        ChemElement(21, "Sc", "Scandium", .transitionMetal, .solid, tint: 0xC3C9D2,
                    "Makes bike frames light and strong."),
        ChemElement(22, "Ti", "Titanium", .transitionMetal, .solid, tint: 0xB6BDC7,
                    "As strong as steel but much lighter, so jets are built from it."),
        ChemElement(23, "V", "Vanadium", .transitionMetal, .solid, tint: 0xAEB6BF,
                    "Added to steel to make spanners that don't snap."),
        ChemElement(24, "Cr", "Chromium", .transitionMetal, .solid, tint: 0xDDE4EC,
                    "The shiny mirror coating on taps and bumper bars."),
        ChemElement(25, "Mn", "Manganese", .transitionMetal, .solid, tint: 0xA9A6A0,
                    "Makes steel tough. It can also turn glass purple."),
        ChemElement(26, "Fe", "Iron", .transitionMetal, .solid, tint: 0xA6A9AD,
                    "Makes your blood red and makes bridges strong."),
        ChemElement(27, "Co", "Cobalt", .transitionMetal, .solid, tint: 0x8FA3C4,
                    "Gives glass and paint a deep blue colour."),
        ChemElement(28, "Ni", "Nickel", .transitionMetal, .solid, tint: 0xC7C6B4,
                    "Coins are made of it, and it hardly ever rusts."),
        ChemElement(29, "Cu", "Copper", .transitionMetal, .solid, tint: 0xC77B3F,
                    "The orange metal inside electric wires. It turns green outside."),
        ChemElement(30, "Zn", "Zinc", .transitionMetal, .solid, tint: 0xBFC7CC,
                    "Coats metal so it can't rust. It's also in sunscreen."),
        ChemElement(31, "Ga", "Gallium", .otherMetal, .solid, tint: 0xC9CEd6,
                    "A metal that melts in your hand."),
        ChemElement(32, "Ge", "Germanium", .metalloid, .solid, tint: 0x8C93A0,
                    "One of the first materials used to build computers."),
        ChemElement(33, "As", "Arsenic", .metalloid, .solid, tint: 0x8A8073,
                    "Very poisonous, so nobody keeps it at home."),
        ChemElement(34, "Se", "Selenium", .nonmetal, .solid, tint: 0x8C4A3A,
                    "Your body needs a tiny bit of it every day."),
        ChemElement(35, "Br", "Bromine", .halogen, .liquid, tint: 0xA13B22,
                    "One of only two elements that are liquid at room temperature."),
        ChemElement(36, "Kr", "Krypton", .nobleGas, .gas, tint: 0x8FE3FF,
                    "A real gas, not just Superman's planet."),
        ChemElement(37, "Rb", "Rubidium", .alkaliMetal, .solid, tint: 0xE0DCD0,
                    "It melts if you leave it out on a hot day."),
        ChemElement(38, "Sr", "Strontium", .alkalineEarth, .solid, tint: 0xDCD9CE,
                    "Makes fireworks burn bright red."),
        ChemElement(39, "Y", "Yttrium", .transitionMetal, .solid, tint: 0xC1C7D0,
                    "Made the red glow in old TV screens."),
        ChemElement(40, "Zr", "Zirconium", .transitionMetal, .solid, tint: 0xC8CDD6,
                    "Its crystals look so much like diamonds that people wear them."),
        ChemElement(41, "Nb", "Niobium", .transitionMetal, .solid, tint: 0xA8AEB8,
                    "Used in magnets strong enough to make trains float."),
        ChemElement(42, "Mo", "Molybdenum", .transitionMetal, .solid, tint: 0xA3A9B3,
                    "Keeps engine parts slippery so they don't grind."),
        ChemElement(43, "Tc", "Technetium", .transitionMetal, .solid, tint: 0x9AA4B4,
                    "The first element that people made in a lab."),
        ChemElement(44, "Ru", "Ruthenium", .transitionMetal, .solid, tint: 0xAFB6C0,
                    "A tiny bit makes computer hard drives hold more."),
        ChemElement(45, "Rh", "Rhodium", .transitionMetal, .solid, tint: 0xE2E8F0,
                    "Rarer than gold, and even shinier."),
        ChemElement(46, "Pd", "Palladium", .transitionMetal, .solid, tint: 0xD3D9E2,
                    "Cleans the fumes coming out of cars."),
        ChemElement(47, "Ag", "Silver", .transitionMetal, .solid, tint: 0xE8ECF2,
                    "The best metal in the world at carrying electricity."),
        ChemElement(48, "Cd", "Cadmium", .transitionMetal, .solid, tint: 0xC6C2B4,
                    "It made bright yellow paint, but it turned out to be poisonous."),
        ChemElement(49, "In", "Indium", .otherMetal, .solid, tint: 0xCED4DC,
                    "It's what makes touchscreens work."),
        ChemElement(50, "Sn", "Tin", .otherMetal, .solid, tint: 0xD2D6DC,
                    "Tin cans. It squeaks when you bend it."),
        ChemElement(51, "Sb", "Antimony", .metalloid, .solid, tint: 0xA5AAB2,
                    "People used it as black eye make-up thousands of years ago."),
        ChemElement(52, "Te", "Tellurium", .metalloid, .solid, tint: 0x9EA3AB,
                    "Eat a speck and you smell like garlic for weeks."),
        ChemElement(53, "I", "Iodine", .halogen, .solid, tint: 0x6B4BA8,
                    "Makes purple smoke, and it gets painted on cuts to kill germs."),
        ChemElement(54, "Xe", "Xenon", .nobleGas, .gas, tint: 0xA9C6FF,
                    "Makes the super bright headlights on some cars."),
        ChemElement(55, "Cs", "Caesium", .alkaliMetal, .solid, tint: 0xF0DFA8,
                    "The world's most accurate clocks run on it."),
        ChemElement(56, "Ba", "Barium", .alkalineEarth, .solid, tint: 0xD8D5C8,
                    "Doctors get you to drink it so your tummy shows up on an X-ray."),
        ChemElement(57, "La", "Lanthanum", .rareEarth, .solid, tint: 0xC2C8D2,
                    "Goes into camera lenses to make photos sharp."),
        ChemElement(58, "Ce", "Cerium", .rareEarth, .solid, tint: 0xBFC5CF,
                    "It's the spark in a lighter."),
        ChemElement(59, "Pr", "Praseodymium", .rareEarth, .solid, tint: 0xBEC8C2,
                    "Colours welding goggles so bright sparks don't hurt your eyes."),
        ChemElement(60, "Nd", "Neodymium", .rareEarth, .solid, tint: 0xC0C6D0,
                    "Makes the strongest magnets you can buy."),
        ChemElement(61, "Pm", "Promethium", .rareEarth, .solid, tint: 0xB8C0CC,
                    "So rare there is almost none of it on Earth."),
        ChemElement(62, "Sm", "Samarium", .rareEarth, .solid, tint: 0xBAC2CE,
                    "Its magnets keep working even when they get very hot."),
        ChemElement(63, "Eu", "Europium", .rareEarth, .solid, tint: 0xC5CBD5,
                    "Makes the red glow in screens and the secret marks on banknotes."),
        ChemElement(64, "Gd", "Gadolinium", .rareEarth, .solid, tint: 0xC0C6D2,
                    "Helps hospital scanners see inside people."),
        ChemElement(65, "Tb", "Terbium", .rareEarth, .solid, tint: 0xB9C1CD,
                    "Glows green under an ultraviolet light."),
        ChemElement(66, "Dy", "Dysprosium", .rareEarth, .solid, tint: 0xBDC4D0,
                    "Hides inside the motors of electric cars."),
        ChemElement(67, "Ho", "Holmium", .rareEarth, .solid, tint: 0xBBC3CF,
                    "Makes the strongest magnetic fields humans can build."),
        ChemElement(68, "Er", "Erbium", .rareEarth, .solid, tint: 0xC2C9D4,
                    "Keeps internet signals strong in cables under the sea."),
        ChemElement(69, "Tm", "Thulium", .rareEarth, .solid, tint: 0xB7BFCB,
                    "The rarest of the rare earths you can actually dig up."),
        ChemElement(70, "Yb", "Ytterbium", .rareEarth, .solid, tint: 0xC6CCD6,
                    "Used in clocks even more accurate than caesium ones."),
        ChemElement(71, "Lu", "Lutetium", .rareEarth, .solid, tint: 0xC4CAD4,
                    "Helps scanners find things hiding inside the body."),
        ChemElement(72, "Hf", "Hafnium", .transitionMetal, .solid, tint: 0xAEB5C0,
                    "Handles heat so well that rocket nozzles are lined with it."),
        ChemElement(73, "Ta", "Tantalum", .transitionMetal, .solid, tint: 0xA9B0BB,
                    "There is a tiny bit of it in every mobile phone."),
        ChemElement(74, "W", "Tungsten", .transitionMetal, .solid, tint: 0x9BA3AE,
                    "Needs more heat to melt than any other metal."),
        ChemElement(75, "Re", "Rhenium", .transitionMetal, .solid, tint: 0xB0B7C2,
                    "Goes into jet engines that get incredibly hot."),
        ChemElement(76, "Os", "Osmium", .transitionMetal, .solid, tint: 0x8FA0B8,
                    "The densest element. A cup of it would be too heavy to lift."),
        ChemElement(77, "Ir", "Iridium", .transitionMetal, .solid, tint: 0xD6DCE4,
                    "A layer of it in the rocks tells us when the dinosaurs died out."),
        ChemElement(78, "Pt", "Platinum", .transitionMetal, .solid, tint: 0xDDE3EA,
                    "Wedding rings are made from it because it never tarnishes."),
        ChemElement(79, "Au", "Gold", .transitionMetal, .solid, tint: 0xF2C038,
                    "Never rusts and never fades, which is why treasure still shines."),
        ChemElement(80, "Hg", "Mercury", .transitionMetal, .liquid, tint: 0xCED5DE,
                    "A silver metal that is liquid. It rolls around like a ball."),
        ChemElement(81, "Tl", "Thallium", .otherMetal, .solid, tint: 0xB6BCC6,
                    "So poisonous it is kept locked away."),
        ChemElement(82, "Pb", "Lead", .otherMetal, .solid, tint: 0x9298A6,
                    "Heavy and soft, and it blocks X-rays."),
        ChemElement(83, "Bi", "Bismuth", .otherMetal, .solid, tint: 0xE07BB8,
                    "Grows into square rainbow-coloured crystals."),
        ChemElement(84, "Po", "Polonium", .otherMetal, .solid, tint: 0xB9B0A0,
                    "Marie Curie found it and named it after Poland."),
        ChemElement(85, "At", "Astatine", .halogen, .solid, tint: 0x9A8E7E,
                    "The rarest natural element on the whole planet."),
        ChemElement(86, "Rn", "Radon", .nobleGas, .gas, tint: 0xFF9AD5,
                    "An invisible gas that seeps up out of the ground."),
        ChemElement(87, "Fr", "Francium", .alkaliMetal, .solid, tint: 0xC9C0AE,
                    "It disappears within minutes of being made."),
        ChemElement(88, "Ra", "Radium", .alkalineEarth, .solid, tint: 0xC9F0D0,
                    "It glows in the dark all by itself."),
        ChemElement(89, "Ac", "Actinium", .actinide, .solid, tint: 0xA8D8F0,
                    "Glows a faint blue in a dark room."),
        ChemElement(90, "Th", "Thorium", .actinide, .solid, tint: 0xB2BAC6,
                    "Named after Thor, the god of thunder."),
        ChemElement(91, "Pa", "Protactinium", .actinide, .solid, tint: 0xAEB6C2,
                    "One of the rarest and most expensive elements there is."),
        ChemElement(92, "U", "Uranium", .actinide, .solid, tint: 0xA9B49C,
                    "Powers nuclear submarines and power stations."),
        ChemElement(93, "Np", "Neptunium", .actinide, .solid, tint: 0xAAB2BE,
                    "Named after the planet Neptune."),
        ChemElement(94, "Pu", "Plutonium", .actinide, .solid, tint: 0xB4AEA4,
                    "Powers the spacecraft that fly far away from the Sun."),
        ChemElement(95, "Am", "Americium", .actinide, .solid, tint: 0xB6BEC8,
                    "There is a speck of it inside your smoke alarm."),
        ChemElement(96, "Cm", "Curium", .actinide, .solid, tint: 0xB0B8C4,
                    "Named after Marie and Pierre Curie."),
        ChemElement(97, "Bk", "Berkelium", .actinide, .solid, tint: 0xB2BAC4,
                    "Made in a lab in Berkeley, California."),
        ChemElement(98, "Cf", "Californium", .actinide, .solid, tint: 0xB4BCC6,
                    "Used to hunt for gold and oil underground."),
        ChemElement(99, "Es", "Einsteinium", .actinide, .solid, tint: 0xAEB6C0,
                    "Named after Albert Einstein."),
        ChemElement(100, "Fm", "Fermium", .actinide, .solid, tint: 0xACB4BE,
                    "Only ever made a few atoms at a time."),
        ChemElement(101, "Md", "Mendelevium", .actinide, .solid, tint: 0xAAB2BC,
                    "Named after the man who invented the periodic table."),
        ChemElement(102, "No", "Nobelium", .actinide, .solid, tint: 0xA8B0BA,
                    "Named after Alfred Nobel, who started the Nobel Prizes."),
        ChemElement(103, "Lr", "Lawrencium", .actinide, .solid, tint: 0xA6AEB8,
                    "It vanishes seconds after it is made."),
        ChemElement(104, "Rf", "Rutherfordium", .transitionMetal, .solid, tint: 0xA4ACB6,
                    "Made by smashing atoms into each other."),
        ChemElement(105, "Db", "Dubnium", .transitionMetal, .solid, tint: 0xA2AAB4,
                    "Named after a science town in Russia."),
        ChemElement(106, "Sg", "Seaborgium", .transitionMetal, .solid, tint: 0xA0A8B2,
                    "Named after a scientist while he was still alive."),
        ChemElement(107, "Bh", "Bohrium", .transitionMetal, .solid, tint: 0x9EA6B0,
                    "Named after Niels Bohr, who drew the first picture of an atom."),
        ChemElement(108, "Hs", "Hassium", .transitionMetal, .solid, tint: 0x9CA4AE,
                    "Only a handful of atoms have ever existed."),
        ChemElement(109, "Mt", "Meitnerium", .transitionMetal, .solid, tint: 0x9AA2AC,
                    "Named after Lise Meitner, who worked out how to split the atom."),
        ChemElement(110, "Ds", "Darmstadtium", .transitionMetal, .solid, tint: 0x98A0AA,
                    "Made in a German town called Darmstadt."),
        ChemElement(111, "Rg", "Roentgenium", .transitionMetal, .solid, tint: 0x969EA8,
                    "Named after the man who discovered X-rays."),
        ChemElement(112, "Cn", "Copernicium", .transitionMetal, .solid, tint: 0x949CA6,
                    "Named after Copernicus, who worked out the Earth goes round the Sun."),
        ChemElement(113, "Nh", "Nihonium", .otherMetal, .solid, tint: 0x929AA4,
                    "The first element ever discovered in Japan."),
        ChemElement(114, "Fl", "Flerovium", .otherMetal, .solid, tint: 0x9098A2,
                    "Named after a Russian physics lab."),
        ChemElement(115, "Mc", "Moscovium", .otherMetal, .solid, tint: 0x8E96A0,
                    "Named after the city of Moscow."),
        ChemElement(116, "Lv", "Livermorium", .otherMetal, .solid, tint: 0x8C949E,
                    "Named after a laboratory in California."),
        ChemElement(117, "Ts", "Tennessine", .halogen, .solid, tint: 0x8A929C,
                    "Named after the American state of Tennessee."),
        ChemElement(118, "Og", "Oganesson", .nobleGas, .gas, tint: 0xC9A0FF,
                    "The heaviest element ever made, and the very last box on the table.")
    ]

    static func element(_ z: Int) -> ChemElement { all[z - 1] }

    /// The 20 that get taught first, used for the "easy start" pool.
    static let firstTwenty = Array(all.prefix(20))
}
